### ISSUE TITLE
inet:sockname(S) returns {error,enotimpl}

### ISSUE THREAD

**Issue by krant** [cloudozer/ling#127]
{ok, S} = gen_tcp:listen(0, [{active, false}, binary]),
    {ok, {_, Port}} = inet:sockname(S), %% crash here

**Comment by EarlGray** [comment]
Fixed by 

https://github.com/cloudozer/ling/commit/6d00527f94bd32b10e52ceb54339696b9d347f0b
https://github.com/cloudozer/ling/commit/4c5425f71ec780d3299e8e8427d9c8004da0d4e0
