### ISSUE TITLE
Compatibility - "nofit" errors?

### ISSUE THREAD

**Issue by arjan** [cloudozer/ling#129]
I'm trying ling on several projects and notice that many beam -> ling conversions fail with `nofit` errors.

e.g.:
```
Compile: _build/dev/lib/cowboy/ebin/cowboy_websocket.beam
escript: exception error: {nofit,l_bs_init_bits,[7,0,1,{x,1}]}
```

and
```
Compile: _rel/xx/lib/bear-0.8.1/ebin/bear.beam
escript: exception error: {nofit,l_fnegate,[{fr,0},{fr,0}]}
```

I guess these have to do with BEAM VM opcode translation / compatiblity? What's the approach to errors like these? I've tried compiling the `.beam` files with different Erlang versions (R16, R17) but the result is always the same.

**Comment by krant** [comment]
Thank you for report. You are right, it is our translator. The most rightful approach is to narrow down error triggering code snippet and insert it to bc/sample dir, to help our toolchain deduce missing opcodes. Or simply post an issue here just like you did. I have added missing opcode emitted by cowboy sources. Unfortunately, bear sources did not reproduced any error. Can you check it one again with latest LING?

**Comment by arjan** [comment]
Thanks for the quick response!
Indeed I can also not reproduce the bear compilation error with the last ling.

However, when trying Elixir, I get this one:

```
Compile: _build/dev/lib/conform/ebin/Elixir.Conform.Schema.SchemaError.beam
escript: exception error: {nofit,get_map_element,[{f,13},{x,0},{a,message},{x,0}]}
  in function  ling_iopvars:fit_args/2 (bc/ling_iopvars.erl, line 2264)
```

**Comment by krant** [comment]
Added another missing opcode, Elixir should compile now.

**Comment by krant** [comment]
No more complaints, seems to be fixed \_(ツ)_/¯
