### ISSUE TITLE
network interface doesn't load in ling

### ISSUE THREAD

**Issue by kansi** [cloudozer/ling#136]
I am trying to run a simple hello world cowboy image (build from here https://github.com/ninenines/cowboy/tree/master/examples/hello_world) on ling. Following is my domain_config

    name = "hello_world"
    kernel = "hello_world.img"
    extra = "-home /hello_world -pz /hello_world/deps/cowboy/ebin /hello_world/deps/cowlib/ebin /hello_world/deps/ranch/ebin /hello_world/ebin"
    vif = ["mac=aa:bb:cc:dd:ee:ff, bridge=xenbr0"]

when I boot using `xl create domain_config -c` and the ling vm starts successfully. I can see a virtual interface created on the host but the shell is not connected to any network interface. I check it using `inet:getif()` which gives `{error, einval}`.

**Comment by EarlGray** [comment]
`inet:getif()` is not implemented in Ling, indeed. Use `inet:getifaddrs()` instead.

Also, network configuration options must be specified in `extra` like this (replace the specified IPs with your network parameters): 
```
-ipaddr 192.168.1.8 -netmask 255.255.0.0 -gateway 192.168.1.1` 
```

**Comment by kansi** [comment]
@EarlGray  ok that worked ! thanks  but I wish to dynamically allocate ip using the dhcp server. How do I go about that ?

**Comment by kansi** [comment]
solved by using -dhcp in extra.
