### ISSUE TITLE
unable to boot lingvm using virsh

### ISSUE THREAD

**Issue by kansi** [cloudozer/ling#138]
I am trying to run a simple hello world cowboy image (build from here https://github.com/ninenines/cowboy/tree/master/examples/hello_world) on ling.  Following is my domain config

```
name = "hello_world"
kernel = "hello_world.img"
extra = "-home /hello_world -pz /hello_world/deps/cowboy/ebin /hello_world/deps/cowlib/ebin /hello_world/deps/ranch/ebin /hello_world/ebin"
vif = ["mac=aa:bb:cc:dd:ee:ff, bridge=xenbr0"]
```

I converted domain_config file into xml format and tried to run it using 

```
$ virsh -c xen:///system create domain_config.xml
```

but the command fails. I tried looking into the logs and found the following error message in the bootloader log

```
RuntimeError: Unable to find partition containing kernel
```

How do i resolve this ?

**Comment by maximk** [comment]
There must be a problem with libvirt config or domain_config.xml. In general, LING images work with libvirt. Once it was a primary method to spawn them. Note that it is possible to load ELF images (including LING) using chain-booting (using pygrub bootloader).

**Comment by EarlGray** [comment]
Perhaps, the problem is related to the `domain_config.xml` extension?

**Comment by kansi** [comment]
I specifed the emulator using 

```
<emulator>/usr/sbin/xen</emulator>
```

and it worked. I also had to specify absolute path for the kernel.
