### ISSUE TITLE
file:sendfile() does not work

### ISSUE THREAD

**Issue by maximk** [cloudozer/ling#32]
This happens with the new version of the website when serving non-HTML content:

=ERROR REPORT==== 3-Jan-2015::07:11:44 ===
Ranch listener www had connection process started with cowboy_protocol:start_link/4 at <0.164.0> exit with reason: {undef,[{prim_file,sendfile,[{file_descriptor,prim_file,{<0.25.0>,52,binary}},#Port<0.5.0>,0,0,8191,[],[],[{chunk_size,8191}]],[]},{file,sendfile,8,[{file,"file.erl"},{line,1258}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,133}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,120}]},{cowboy_static,'-get_file/2-fun-0-',3,[{file,"src/cowboy_static.erl"},{line,278}]},{cowboy_req,reply,4,[{file,"src/cowboy_req.erl"},{line,784}]},{cowboy_rest,respond,3,[{file,"src/cowboy_rest.erl"},{line,973}]},{cowboy_rest,set_resp_body,2,[{file,"src/cowboy_rest.erl"},{line,849}]}]}

**Comment by krant** [comment]
Fixed
